jakartaee/messaging

pom.xml

Added GPG release profile with--pinentry-mode loopback

---

pom.xml

Updated to latest 1.0.2 version of EE4J master pom

---

README.md
pom.xml

Signed-off-by: Maxim Nesen <maxim.nesen@oracle.com>

Prepare EE4J_8 pom for release

---

NOTICE.md

Add missing NOTICE file

---

pom.xml

Set version to 2.0.2-SNAPSHOT

---

README.md

Task-Url: https://github.com/eclipse-ee4j/jms-api/issues/209

209: Fix the README

---

.gitignore
api/pom.xml
api/src/main/javadoc/doc-files/speclicense.html

Updated Javadoc to latest Jakarta EE 8 requirements

---

api/pom.xml

Update API pom with description and XML prolog

---

spec/src/main/asciidoc/messaging-spec.adoc

Update doctitle to remove version number

---

api/pom.xml
pom.xml
spec/pom.xml

* Set API version to x.y.z
* Update plugin versions
* Update spec plugin
* Deabstract abstractions that are only used once
* Ordered poms according to Maven default order

Updated pom files

---

.gitignore

Updated gitignore to exclude Eclipse and other files

---

api/pom.xml
pom.xml
spec/pom.xml

Update pom versions

---

api/src/main/java/jakarta/jms/JMSConnectionFactoryDefinition.java
api/src/main/java/jakarta/jms/JMSDestinationDefinition.java

#255 Updated Javadoc references to common annotations

---

api/pom.xml
pom.xml
spec/pom.xml

#255 Prepare for RC1 release

---

CONTRIBUTING.md

Add info about contributing

---

api/pom.xml
pom.xml
spec/pom.xml

* Update versions
* Attached source jar
* Tidying

Small cleanup of poms

---

NOTICE.md

Update NOTICE file with the Jakarta Messaging name

---

api/pom.xml
pom.xml
spec/pom.xml

To start development on the new version which should be 3.1.
Replaces #280.

Set 3.1 version

---

api/src/main/java/jakarta/jms/JMSDestinationDefinition.java

Update JMSDestinationDefinition#properties description

---

.github/workflows/maven.yml

- This could serve as CI for #189

Setup GitHub Actions

---

README.md

- Fixes discrepancy introduced in #294

Update maven version to currently enforced one

---

api/src/main/java/jakarta/jms/JMSException.java
api/src/main/java/jakarta/jms/QueueRequestor.java
api/src/main/java/jakarta/jms/TopicRequestor.java

Cosmetic, mainly to execute GHAs for the first time here.

Remove useless parentheses

---

api/src/main/java/jakarta/jms/package.html

With https://github.com/jakartaee/messaging/blob/a59f98b45372f83447778ea22a7fc67797292e23/api/pom.xml#L135 already in place, I guess this could be updated too.

Update spec reference

---

README.md

Update required JDK

---

api/pom.xml

This property is also used by javadoc plugin.

Set target release with property

---

api/pom.xml
pom.xml
spec/pom.xml

Add parent to the API module
This is to be able to update all the versions at once during a release.

Synchronize versions of all Maven modules

---

api/pom.xml

Use explicit and empty relativePath to override default ../pom.xml

---

spec/src/main/asciidoc/messaging-spec.adoc

Fix "Example using the simplified API and injection"
